"""create portfolio_holdings table

Revision ID: 3a11cbc5313a
Revises: 6bb8d5a9a087
Create Date: 2026-07-18 15:52:46.895261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a11cbc5313a'
down_revision: Union[str, None] = '6bb8d5a9a087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_holdings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_holdings_user_id'), 'portfolio_holdings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_current_version', 'strategies', type_='foreignkey')
    op.drop_index(op.f('ix_portfolio_holdings_user_id'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    # ### end Alembic commands ###
