"""create orders, decision_logs, portfolio_snapshots tables

Revision ID: 6bb8d5a9a087
Revises: ebccde044638
Create Date: 2026-07-11 15:55:16.472047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bb8d5a9a087'
down_revision: Union[str, None] = 'ebccde044638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('positions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_logs',
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules_triggered_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('risk_approved', sa.Boolean(), nullable=False),
    sa.Column('risk_reason', sa.String(), nullable=False),
    sa.Column('explanation_text', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('alpaca_order_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='order_side'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='order_type'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PARTIALLY_FILLED', 'FILLED', 'CANCELED', 'REJECTED', name='order_status'), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('filled_avg_price', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpaca_order_id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('decision_logs')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
