"""create strategy and strategy_version tables

Revision ID: ebccde044638
Revises: 
Create Date: 2026-07-08 17:12:42.047618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebccde044638'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'VALIDATED', 'BACKTESTED', 'CONFIRMED', 'ACTIVE', 'PAUSED', 'CLOSED', name='strategy_state'), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['strategy_versions.id'], name='fk_current_version', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'CHAT', name='strategy_version_source'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version_number', name='uq_strategy_version_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_versions')
    op.drop_table('strategies')
    sa.Enum(name='strategy_version_source').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='strategy_state').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###